### ISSUE TITLE
add weather warnings (yellow, orange, red)

### ISSUE THREAD

**Issue by fvoncken** [CNugteren/NLWeer#13]
Nice app! It would be nicer if weather warnings can be added (https://knmi.nl/nederland-nu/weer/waarschuwingen/), because of the importance of this information. Further, good work!

**Comment by CNugteren** [comment]
Yes, makes sense. I'll add that in the next iteration.

**Comment by CNugteren** [comment]
I've added it now and it looks like this:

![waarschuwingen](https://user-images.githubusercontent.com/1162108/87438683-2615b080-c5f0-11ea-9ee2-f1090437ce62.png)

I've only decided to do it now, because with the latest feature of selecting which views appear in the menu it no longer becomes clutter for people who don't care about the weather warnings, e.g.:

![knmi_kaarten](https://user-images.githubusercontent.com/1162108/87438678-24e48380-c5f0-11ea-92f6-774a70650c77.png)

This is both now in master and will be part of the next release.

**Comment by CNugteren** [comment]
I'm closing this, since this is implemented in the [just released v1.4.0 version](https://github.com/CNugteren/NLWeer/releases). It will be available on F-Droid automatically in a few days.
