### ISSUE TITLE
Add shortcuts for pages

### ISSUE THREAD

**Issue by GithubBram** [CNugteren/NLWeer#15]
Since swiping seems not feasible (issue #8), is it possible to add shortcuts to the pages, so that with one click (instead of two using the menu) a page will be selected immedeately? See "artist impression" in attached image, but then the logos being white on a black background.

![NLweer_shortcuts](https://user-images.githubusercontent.com/45642947/87231518-288dc580-c3b8-11ea-9e3e-b0a3f28c288c.jpg)

**Comment by CNugteren** [comment]
Good suggestion. I plan to work on the app again soon, and I'll definitely try out something like this.

**Comment by CNugteren** [comment]
I tried to implement something (the design at least - not the functionality yet) based on common Android Material design components and guidelines, and I ended up with this:

![bottom_nav](https://user-images.githubusercontent.com/1162108/87465173-80286d00-c614-11ea-84cc-146e86853c3a.png)

Problem is that this can fit at most 5 icons (otherwise they will become too small for certain screens to touch). And thus a potential solution could be that this can show the user's 5 most favorite pages for example. That would require a bit extra effort of course, but it could be done.

However, I see a few drawbacks as well:
* Users might be confused when seeing this at first and don't even look for the real menu at all, thinking there are only 5 items
* Showing the full text names below the icons is too long, but with icon only it might not be sufficient
* We loose a lot of space in landscape mode

So I'm not 100% convinced this is a good idea. Perhaps I should revisit the swipe left/right again (or top/bottom?) given the newly added feature of users selecting which items they want to show in the navigation menu.

**Comment by CNugteren** [comment]
Since this idea didn't work out nicely (see my previous message), I've implemented something else: a back & forward button. They will navigate only among the maps the user chooses to be visible in the settings screen. Here's what it looks like:
![nlweer_navigation](https://user-images.githubusercontent.com/1162108/88708158-85f17880-d113-11ea-88c5-af12bb0fc7c0.png)
To reduce clutter, it is by default disabled and can be enabled in the settings.

Do you think this (partially) solves your navigation issue?

**Comment by GithubBram** [comment]
Hello Cedric, this looks very nice, for me it is similar to swiping (comparable finger movement).

**Comment by CNugteren** [comment]
I'm closing this, since this is implemented in the [just released v1.4.0 version](https://github.com/CNugteren/NLWeer/releases). It will be available on F-Droid automatically in a few days.
