### ISSUE TITLE
Location marker without center

### ISSUE THREAD

**Issue by PanderMusubi** [CNugteren/NLWeer#18]
Please, use a location marker without a tiny circle in the center in order to more easily distinguise then from earthquakes and to show more details inside the cirle, which are probably the most of interest to the user.

![Screenshot_20200814-192800_NLWeer](https://user-images.githubusercontent.com/198964/90291025-3fc04700-de7f-11ea-9f03-7e8d40c8adb5.png)

**Comment by CNugteren** [comment]
Since I'm not sure every user shares this opinion (and I definitely doubt many people are confused by the rare earthquake marker), I've made your request into a new preference with the current situation as the default behaviour. Here's an example of setting a yellow single circle instead.

![location_marker](https://user-images.githubusercontent.com/1162108/90432112-5d352100-e0ca-11ea-8f8b-4a66dff82c85.png)
![marker_preferences](https://user-images.githubusercontent.com/1162108/90432115-5dcdb780-e0ca-11ea-9f97-123128471170.png)


This is now in master.

**Comment by PanderMusubi** [comment]
Thanks for removing the center. Will the yellow not be hidden when a thunderstorm of yellow crosses is under it? The red color was not an issue. If you do want to change it, perhaps use magenta, but I'm fin with red.

**Comment by CNugteren** [comment]
It actually is an option, with red being the default. Purple, yellow, green, and orange are other options at the moment.

**Comment by CNugteren** [comment]
Closing this issue since it is resolved and in master (see earlier message). It will be part of the next release.
