### ISSUE TITLE
Please add KNMI Weerkaarten

### ISSUE THREAD

**Issue by bodypilot** [CNugteren/NLWeer#23]
I like this app, especially because it´s available through F-Droid and works perfectly with a de-Googlefied phone.
Can you please add the synoptic maps shown here: https://www.knmi.nl/nederland-nu/weer/waarschuwingen-en-verwachtingen/weerkaarten?

**Comment by CNugteren** [comment]
Thanks for the suggestion. I will add them, I will let you know here when it is ready.

**Comment by CNugteren** [comment]
This is now implemented. It was a bit trickier, since the maps on the KNMI website actually don't have a fixed URL. Instead, they have the current day + hour (rounded down to either 00 or 12) and then the same but 12 or 24 hours later. But anyway this is now implemented and working:
![synoptic_map1](https://user-images.githubusercontent.com/1162108/99908199-8d034e80-2ce1-11eb-9b22-3d366d59559a.png)
![synoptic_map2](https://user-images.githubusercontent.com/1162108/99908201-8e347b80-2ce1-11eb-9a18-cc417f47037b.png)
I choose not to include localisation on these maps, since they show the whole Europe.

**Comment by CNugteren** [comment]
This is now available in version 1.6.0, which was just released on GitHub and will be available in F-Droid automatically in a few days.

**Comment by bodypilot** [comment]
Thank you for adding these maps (and the "Extremen" map, #24 ). I've downloaded 1.6.0 from GitHub and it works perfectly.
Minor nitpick: the website usually shows 4 synoptic maps (mostly in the morning), NLWeer only shows 3.

![Screenshot_20201126-070848_Bromite](https://user-images.githubusercontent.com/1009816/100382477-bdb5f180-301b-11eb-8199-8a57fb12de60.png)
![Screenshot_20201125-112033_Bromite](https://user-images.githubusercontent.com/1009816/100382478-be4e8800-301b-11eb-93b8-0f0a65ababa2.png)

**Comment by CNugteren** [comment]
Hmm, OK. But I don't think that this +36h is available in the afternoon. Although nothing is written here right now, I suspect this map is from October 29th still:
https://cdn.knmi.nl/knmi/map/page/weer/waarschuwingen_verwachtingen/weerkaarten/PL2900_large.gif
So that would be a conditional map, which would require extra logic in the app based on the time, which I don't think is that easy to implement.

**Comment by bodypilot** [comment]
Okay, thanks. In that case it's fine as it is.
Again, thank you for implementing this!
