### ISSUE TITLE
Please add https://www.knmi.nl/nederland-nu/weer/actueel-weer/extremen

### ISSUE THREAD

**Issue by bodypilot** [CNugteren/NLWeer#24]
I'm hoping two separate feature requests is what is appropriate here...
Can you please add the maps shown at https://www.knmi.nl/nederland-nu/weer/actueel-weer/extremen (I'm particularly interested in the "Hoeveelheid neerslag"-map (rainfall last 24 hours).

**Comment by CNugteren** [comment]
Thank you for the suggestion. I will add those maps as well. Since more and more maps are being added, I will first however refactor the code a bit such that adding a new map requires less code, to make it easier in the future and also to avoid code duplication. I will let you know here when the maps are added.

**Comment by CNugteren** [comment]
This is now implemented. All seven maps are available as optional maps:
![seven_new_knmi_maps](https://user-images.githubusercontent.com/1162108/99879690-ae473a80-2c0e-11eb-81c3-51f814be88a0.png)

**Comment by CNugteren** [comment]
This is now available in version 1.6.0, which was just released on GitHub and will be available in F-Droid automatically in a few days.
