### ISSUE TITLE
Pluimverwachting

### ISSUE THREAD

**Issue by WouterSuijker** [CNugteren/NLWeer#28]
Could you please add the possibility to show the Pluimverwachting van de KNMI en Buienradar website?

https://www.buienradar.nl/nederland/verwachtingen/de-pluim

https://www.knmi.nl/nederland-nu/weer/waarschuwingen-en-verwachtingen/weer-en-klimaatpluim

It would make the app complete for me and there wont be the need of using an extra application just for the Pluim.

Thanks!

**Comment by CNugteren** [comment]
I think it could be a useful addition indeed, however I see a few complications:
* On both sources these are not images but more complicated pieces of HTML
* There are quite a lot of different graphs (temperature, wind, cloud cover, etc.)
* There are different graphs per region, so I'll need to implement a mapping from lon-lat to those regions

Because of this, I don't think it will be simple doing it in the same way as the other graphs in NLWeer. So I suggest the following instead: I just display those webpages in two new screens. That is not too much work, but the user will have to scroll and optionally select a location. What do you think about that?

**Comment by WouterSuijker** [comment]
I would be very pleased with that!

15 jan. 2021 11:51:13 Cedric Nugteren <notifications@github.com>:

> I think it could be a useful addition indeed, however I see a few complications:
> 
* > On both sources these are not images but more complicated pieces of HTML
* > There are quite a lot of different graphs (temperature, wind, cloud cover, etc.)
* > There are different graphs per region, so I'll need to implement a mapping from lon-lat to those regions

**Comment by CNugteren** [comment]
I've added both graphs now, see #29. It is basically just showing the websites with some parts of the layout disabled. Right now it looks as follows:
![Screenshot_1611495079](https://user-images.githubusercontent.com/1162108/105631992-608ac080-5e51-11eb-9843-31698d69a612.png)
![Screenshot_1611495093](https://user-images.githubusercontent.com/1162108/105631994-61bbed80-5e51-11eb-819a-063ff6286c2d.png)

I'll do some on-device testing in the coming days and if it works I'll release a new version of NLWeer.

**Comment by CNugteren** [comment]
Closing this, this is now in version 1.7.0.
