### ISSUE TITLE
Add Buienradar maps

### ISSUE THREAD

**Issue by PanderMusubi** [CNugteren/NLWeer#3]
Please add hail radar (hagelradar)

https://www.buienradar.nl/nederland/neerslag/hagelradar

**Comment by PanderMusubi** [comment]
Possibly also other maps from Buienradar, bit the one for hail specifically.

**Comment by CNugteren** [comment]
I just renamed this issue to make it a bit broader. Yes, I plan to add Buienradar, but I'm currently still waiting for permissions from them. They haven't replied yet, so I asked a second time yesterday.

Meanwhile, there is already a branch `buienradar` that implements a first map as a proof of concept. I'll add the hail-map as well later, but without permission this work is not useful yet.

**Comment by PanderMusubi** [comment]
Any progress? Perhaps contacting them again after the holidays?

**Comment by CNugteren** [comment]
Still no reply, I did asked them again this week though.

In the meantime I've updated the `buienradar` branch to match with master, and also included a rain graph based on the data supplied by Buienradar, which looks currently like this:
![rain_graph](https://user-images.githubusercontent.com/1162108/73138852-c50d1700-4067-11ea-929b-d3d3651c8861.png)

**Comment by PanderMusubi** [comment]
Looks nice. You could send them a message saying, after two/three requests and not hearing from you back, I hereby assume that it is all right that this app uses your data. If not, please contact me to revert inclusion of it. As their data is widely and publically reused and they probably are too busy, this might work.

**Comment by PanderMusubi** [comment]
Or send this in a private message to https://twitter.com/buienradarnl Might land on someone else's desk and prompt a reaction.

**Comment by CNugteren** [comment]
Still no replies, so I have asked again today. Fingers crossed.

**Comment by PanderMusubi** [comment]
Last (but bold) resort might be to ask them publically via Twitter with a deadline.

**Comment by CNugteren** [comment]
I don't have a Twitter account, so someone else would need to do that. But they might have good reasons to say 'no', so being bold might not be the right approach. And just doing it without permissions also (e.g. set a deadline if they don't reply) is not a good solution either, because on their website they say that you can only use the data for a mobile app if you have permissions.

If you really want to use it without permissions, so can always check out the branch, compile the project, and install the app from the apk.

**Comment by PanderMusubi** [comment]
Ah, not being bold in the request, but being bold in contacting them via Twitter. Let me know when you want me to ask them in that way.

**Comment by CNugteren** [comment]
Since I don't seem to get any response from Buienradar, I've decided to go for an alternative approach: let the users determine whether or not they have/need permissions. To illustrate this:
![buienradar_permissions](https://user-images.githubusercontent.com/1162108/76897659-6eb49b80-6894-11ea-80f0-2a766c74a595.png)
Accepting this once will enable the Buienradar maps to show up in the menu.

I'm expecting to be able to finish this in a week or two and draft a new release of NLWeer.

**Comment by PanderMusubi** [comment]
Good solution.

**Comment by CNugteren** [comment]
All implemented and merged to master. There are now 6 buienradar data sources:
1. Rain last hour
2. Drizzle last hour
3. Hail last hour
4. Sunshine
5. Cloud cover
6. Precipitation expectation graph

You can expect a new release with this feature in a week or 2.
