### ISSUE TITLE
Feature request: add KNMI windchill map

### ISSUE THREAD

**Issue by bodypilot** [CNugteren/NLWeer#32]
A feature request very much inspired by today's weather :-)

Please consider adding the "Gevoelstemperatuur" map found at [https://www.knmi.nl/nederland-nu/weer/waarnemingen](https://www.knmi.nl/nederland-nu/weer/waarnemingen)  & https://cdn.knmi.nl/knmi/map/page/weer/actueel-weer/gevoelstemperatuur.png to this wonderful app.

**Comment by CNugteren** [comment]
Good idea, I've just added that map. I'll do some more on device testing in the coming days. It will be available in the next release :-)

**Comment by bodypilot** [comment]
The wind chill map seems to have disappeared from https://www.knmi.nl/nederland-nu/weer/waarnemingen. Perhaps KNMI discontinued it as I can't find it anywhere else. 
Or the KNMI only calculates wind chill during the winter, as https://cdn.knmi.nl/knmi/map/page/weer/actueel-weer/gevoelstemperatuur.png is stuck at March 28th, when day light saving time started this year?

Perhaps this https://www.weerplaza.nl/actueel/windchill/ is a (better?) alternative?

**Comment by CNugteren** [comment]
Ah indeed, https://cdn.knmi.nl/knmi/map/page/weer/actueel-weer/gevoelstemperatuur.png shows the map from the 28th of March. I've asked KNMI what the status is, I'll let you know once I get a response.

The problem with other sources is whether or not it is allowed to share their data in the app, because they typically are commercial companies. I haven't investigated Weerplaza, but I would rather stick to what is currently offered, because those conditions are studied and OK :-)

**Comment by CNugteren** [comment]
I got a response from KNMI and indeed the answer is that this map is only available in the winter period. So I propose to just leave it in the app - users can remove it from their menu if they want.

**Comment by bodypilot** [comment]
Agreed.

I have petitioned the KNMI to also make the windchill-map available outside of winter time.
In case someone wants to do the same: https://www.knmi.nl/over-het-knmi/contact/contactformulier :)

**Comment by CNugteren** [comment]
Closing this, as it will come back in the winter period.
